site_name: Documentación
site_url: https://sitename.example
nav:
  - Inicio: index.md
  - MKdocs: 
    - Uso: pages/usoMKdocs.md
    - Instalación: pages/instalacionMKdocs.md
  - AWS:
    - Uso: pages/usoAWS.md
    - VPC:
      - Creación de VPC y subredes: pages/instalacionVPC.md
    - EC2:
      - Creación de EC2: pages/instalacionEC2.md
      - Instalación de Nginx: pages/Nginx.md
      - Nginx en funcionamiento: pages/NginxFuncionamiento.md
    - ECS:
      - Creación de ECS: pages/creacionECS.md
      - Conexión con RDS: pages/conexionecsrds.md
      - Desplegar Wordpress: pages/desplegarWP.md
    - RDS:
      - Creación de RDS: pages/creacionRDS.md
    - S3:
      - Página estática en S3: pages/paginaestaticas3.md
      - Cloudfront y ACM: pages/Cloudfront.md
    - WAF:
      - Crear una ACL: pages/waf.md
  - Docker:
    - Dockerización de MKdocs: pages/Dockerizacion.md
  - GitHub Actions: pages/GitHubActions.md
  - Terraform:
    - VPC con EC2 y Nginx: pages/TerraEC2.md
    - ECS: pages/TerraECS.md

theme:
  name: material
  language: es
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    annotation: material/plus-circle
  features:
    - header.autohide
    - content.code.copy
  palette: 
# Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo día
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo noche
      primary: blue
      accent: deep orange
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition
  
plugins:
   - glightbox


extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%C3%A1lvarogarc%C3%ADaoca%C3%B1a/
