name: Deploy to Amazon S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1
  PYTHON_VERSION: '3.12.3'
  SOURCE_DIR: 'site'
  CLOUDFRONT_ID: 'EBMV15V4EDAPU'
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: ${{ env.PYTHON_VERSION }}

    - run: pip install -r requirements.txt
    - run: mkdocs build
    - uses: jakejarvis/s3-sync-action@master
      #with:
        #args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }} 
        SOURCE_DIR: ${{ env.SOURCE_DIR }}     

    - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
